= Tooltip for Asciidoctor

Расширение преполагает возможность оборачивания Терминов в html тэг <abbr> для того, чтобы их определения можно было посмотреть прямо в тексте

Работает если у вас в документе есть таблица с двумя колонками и идентификатором - `tnc`:

[#tnc]
|===
|Термины |Определения

|Какой-то термин
|Определение какого-то термина

|===

== Попробовать

. Выполните `npm i asiidoctor`
. Проверьте, что пути указаны верно
+
[source, html]
----
 <script src="node_modules/@asciidoctor/core/dist/browser/asciidoctor.min.js"></script>
<link rel="stylesheet" href="node_modules/@asciidoctor/core/dist/css/asciidoctor.css"></link>
----
. Откройте index.html

== Проблема

Не решен вопрос вхождения меньшего определения в Большее, напрмер:

Есть термин "Кошелек" и "Кошелек Закрытый", если сначала .replace() заменит большее определение, то итоговый текст будет:
[source, html]
----
<abbr title="Определение закрытого кошелька"><abbr title="Определение кошелька">Кошелек</abbr>Закрытый</abbr>
----

А если сначала малое опеределение будет заменено, то большее и вовсе не будет учтено

Оба варианта обозначены в контенте, отображаемом в index.html